name: PDF Maker build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y xfonts-base xfonts-75dpi

      - name: Install wkhtmltopdf
        run: |
          sudo apt install wkhtmltopdf

      - name: Set up Go
        uses: actions/setup-go@v5.0.1
        with:
          go-version: stable

      - name: Build Cmd
        run: go build -v ./cmd/pdf_maker/main.go -o pdf_maker_cmd

      - name: Build Web Service
        run: go build -v ./cmd/webserver/main.go -o pdf_maker_webserver